# Generated by Django 4.0.6 on 2022-07-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('numero_motores', models.IntegerField()),
                ('numero_tripulantes', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('numero_tripulantes_min', models.IntegerField()),
                ('capacidad_carga', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('cantidadMinima', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nave.categoria')),
            ],
            options={
                'verbose_name': 'Nave',
                'verbose_name_plural': 'Naves',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nave.nave')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
