# Generated by Django 4.0.6 on 2022-07-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nave',
            name='cantidadMinima',
        ),
        migrations.RemoveField(
            model_name='nave',
            name='numero_tripulantes_min',
        ),
        migrations.AddField(
            model_name='nave',
            name='combustible',
            field=models.CharField(default='gasolina', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nave',
            name='objetivo',
            field=models.CharField(default='viaje', max_length=50),
            preserve_default=False,
        ),
    ]
